# Generated by Django 4.0.5 on 2023-01-24 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
